### ISSUE TITLE
Redesign: Improve UI of Apply for Loan Screen

### ISSUE THREAD

**Issue by luckyman20** [openMF/mifos-mobile-cn#104]
**Summary:**

There is a scope to improve the design of apply for loan screen of Mifos Mobile CN app.

**Steps to reproduce:**

Open the app -> Home -> Accounts -> Create New Loan Account/Apply For Loan

**Proposed design:**

![Accounts - 2 – 1](https://user-images.githubusercontent.com/20682192/71641563-1d006a00-2cc4-11ea-8b2f-5f2c76d8be0d.png)

![Accounts - 2 – 3](https://user-images.githubusercontent.com/20682192/71641565-27226880-2cc4-11ea-8366-f81aa1905da3.png)

**Comment by laxyapahuja** [comment]
@luckyman20 can I take up this issue?

**Comment by devansh-299** [comment]
@luckyman20 GCI is over can I take up this issue now ?

**Comment by luckyman20** [comment]
Yes, you can.

**Comment by rachittt** [comment]
@laxyapahuja are you working on it ?

**Comment by laxyapahuja** [comment]
> @laxyapahuja are you working on it ?

Not right now. You can work on it.
