### ISSUE TITLE
Redesign: Create Transfer Screen

### ISSUE THREAD

**Issue by luckyman20** [openMF/mifos-mobile-cn#107]
**Summary:**

There should be an **'Transfer'** screen in the app to let users transfer money for payment and other purposes.

**Proposed design:**

![transfer - 2](https://user-images.githubusercontent.com/20682192/71641695-22f74a80-2cc6-11ea-8b03-c74f5f7abe03.png)

![transfer - 3](https://user-images.githubusercontent.com/20682192/71641696-22f74a80-2cc6-11ea-965f-0de20a6aa746.png)

**Comment by punwai** [comment]
@luckyman20 I am just sending you a message here just because I do not know how else I would be able to. I will delete this comment once you've seen it. Would it be possible for you to check a query that I've sent you on Gitter? I understand that you are very busy and I really appreciate it.

**Comment by punwai** [comment]
@luckyman20 Thank you for your response, I really appreciate it. I've responded to your answer on gitter.
