### ISSUE TITLE
feat : Share option is not implemented in Navigation Drawer.

### ISSUE THREAD

**Issue by jatinsachdevame** [openMF/mifos-mobile-cn#131]
**Summary:**
Currently, the share option is not implemented in the Navigation Drawer in DashboardActivity.

**Steps to reproduce:** 
Open the app -> Login -> Navigation Drawer.

How can we reproduce the issue?
Open the app -> Login -> Navigation Drawer.

**Device and Android version:** All devices.

**Comment by jatinsachdevame** [comment]
@luckyman20 I would like to implement this feature. What it is expected to do?

**Comment by rachittt** [comment]
duplicate of #72

**Comment by jatinsachdevame** [comment]
> duplicate of #72

oops, my bad.
