### ISSUE TITLE
Bug in Share button

### ISSUE THREAD

**Issue by garvit984** [openMF/mifos-mobile-cn#141]
**Summary:**
Supposing the permission to write to external storage is not given, it'll ask for permission. When granted it should ideally call the "share image" method, but nothing happens. This is because when the Permission is being granted, it's checking for "CAMERA" permission instead of "WRITE_EXTERNAL_STORAGE" permission. It occurs when the permission is being granted initially and later, this error does not occur.
**Steps to reproduce:**

How can we reproduce the issue?
Click Account Overview
Then click on Profile Image
Then Share button
*Expected Behaviour*

When the Permission is granted for the first time, it should perform the "share" feature without requiring the user to click on the share icon in the app bar. (1 Click on "share" is expected)

*Observed Behaviour*

When the Permission is granted for the first time, nothing happens. The user has to again click on the "share" icon in-app bar to use the share feature. (2 Clicks on "share" is required)

**Device and Android version:**

Redmi 7A Android-9

**Screenshots:**
![share_first_time](https://user-images.githubusercontent.com/54365596/76443009-c6ac5780-63e7-11ea-9e04-0e5a1784e673.gif)

**Comment by garvit984** [comment]
I'll be working on it

**Comment by garvit984** [comment]
@ivary43

**Comment by prajwal27** [comment]
I'll also try to work on this issue.

**Comment by garvit984** [comment]
@prajwal27 This issue has been solved by PR #88 .So I have also stopped working on it.

**Comment by prajwal27** [comment]
@garvit984  This is a issue related to sharing of profile image and not the app.

**Comment by garvit984** [comment]
Okay, sorry, @prajwal27 . I need to tell you that as per contribution guidelines, if someone else is already working on an issue, you need to first ask that person whether he is continuing or not.
I suppose that you will keep this in mind. Otherwise, you have to report your issues.

**Comment by prajwal27** [comment]
@garvit984 Please do not delete your comments. It'll confuse other people when they go through the issue. Also, the issue was created 9 days back and hence thought of contributing. I'll keep this in mind.
