### ISSUE TITLE
Help Feature Does not Work

### ISSUE THREAD

**Issue by garvit984** [openMF/mifos-mobile-cn#150]
Summary:
Clicking on the Help in the navigation drawer opens Home Fragment.
Steps to reproduce:

How can we reproduce the issue?
Click on Help in the navigation drawer

Expected Behaviour
It should have opened the Help Fragment

Observed Behaviour

Home Fragment opens on clicking

Device and Android version:

Redmi 7A Android-9

Screenshots:
![help](https://user-images.githubusercontent.com/54365596/76448507-738ad280-63f0-11ea-88d8-1c561e4d516c.gif)

**Comment by Prashant830** [comment]
Can I solve this problem??
