### ISSUE TITLE
Bug in Bell Icon

### ISSUE THREAD

**Issue by garvit984** [openMF/mifos-mobile-cn#151]
Summary:
Clicking on the Bell button on the dashboard does not do anything.
Steps to reproduce:

How can we reproduce the issue?
Click on Bell Button

Expected Behaviour
It should have opened Notification Activity

Observed Behaviour

Nothing happens on clicking

Device and Android version:

Redmi 7A Android-9

Screenshots:
![no_bell_icon](https://user-images.githubusercontent.com/54365596/76449088-72a67080-63f1-11ea-95d9-6132dce2c74b.gif)

**Comment by priyanka0906** [comment]
@garvit984  can I work on this issue?

**Comment by garvit984** [comment]
It has now been resolved.
