### ISSUE TITLE
User profile is not properly displayed in navigation Drawer

### ISSUE THREAD

**Issue by garvit984** [openMF/mifos-mobile-cn#154]
Name and Photo should be visible in the navigation drawer

**Comment by garvit984** [comment]
I'll be working on it. @abhijitramesh

**Comment by sabya48** [comment]
i am working on it

**Comment by garvit984** [comment]
@sabya48 I am already working on it. Actually I am working on all the issues simultaneously to revamp the app. @sabya48 You can report any other issue  and work on it.

**Comment by sabya48** [comment]
Ok sure
