### ISSUE TITLE
Refresh Animation works endlessly after Filter with no options

### ISSUE THREAD

**Issue by garvit984** [openMF/mifos-mobile-cn#155]
Summary:

When refreshing the dashboard activity with the upward swipe action the loader keeps spinning infinitely

Steps to reproduce:

Click on Accounts on the dashboard
then click on the filter with no options selected.

Expected behaviour:
It should have given the same results as earlier
Refresh the activity properly and stop the refreshing animation once it is refreshed

Observed behaviour:

Refresh animation spinning endlessly without doing anything

Screenshots:
![fiter](https://user-images.githubusercontent.com/54365596/76450051-2eb46b00-63f3-11ea-99fa-8a5fa9680f4a.gif)

**Comment by garvit984** [comment]
I'll be working on it. @therajanmaurya

**Comment by prajwal27** [comment]
@garvit984 Can I work on this issue?

**Comment by garvit984** [comment]
@prajwal27 I am working on this.
