### ISSUE TITLE
refactor: convert null check to kotlin style

### ISSUE THREAD

**Issue by yashraj-iitr** [openMF/mifos-mobile-cn#198]
## Summary

The current null checks in Network.kt can be refactored to more kotlin style.

The following lines of code can be refactored to kotlin style:
1. `return info != null && info.isConnected`
2. `return info != null && info.isConnected &&
                info.type == ConnectivityManager.TYPE_WIFI`
3. `return info != null && info.isConnected &&
                info.type == ConnectivityManager.TYPE_MOBILE`
4. `return info != null && info.isConnected &&
                Network.isConnectionFast(info.type, info.subtype)`

**Comment by Sparsh1212** [comment]
I would like to work on this issue. Please assign this to me.
