### ISSUE TITLE
feat: clicking on person avatar opens customer profile activity

### ISSUE THREAD

**Issue by abhijitramesh** [openMF/mifos-mobile-cn#67]
**Summary:**
The User should be able to view their profile picture on clicking on the picture icon in Dashboard Fragment

**Steps to reproduce:**
Go to dashboard activity click on the person avatar
**Expected behaviour:**
Customer profile activity opens

**Observed behaviour:**

Nothing happens
**Logcat for the issue**

Provide logs for the crash here

**Device and Android version:**

Oxygen OS 9.0.17  for OnePlus6t Mclaren
**Screenshots:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43090559/68528207-8e015200-0311-11ea-8646-97b98b8d8542.gif)

**Comment by deepak-prajapatii** [comment]
I want to work on this issue. Can I go for it?

**Comment by deepak-prajapatii** [comment]
@abhijitramesh can I work on this issue?

**Comment by garvit984** [comment]
It is resolved.
