### ISSUE TITLE
feat: show logged out succesfully toast on loggin out

### ISSUE THREAD

**Issue by abhijitramesh** [openMF/mifos-mobile-cn#69]
**Summary:**

When the user logs out off the app a toast should be shown which says logged out successfully

**Steps to reproduce:**

Go to the Navigation bar and click on logout

**Expected behavior:**

The user gets logged out with a toast showing logged out successfully

**Observed behavior:**

The user gets logged out but no toast is shown.

**Comment by PiyushSharma99** [comment]
I would like to work on this.

**Comment by PiyushSharma99** [comment]
@abhijitramesh Where is the GCI task link? Can you please share?

**Comment by abhijitramesh** [comment]
@PiyushSharma99 someone is already working on this and have claimed the task and hence you are not able to find it 

here is the link:
https://codein.withgoogle.com/dashboard/tasks/5071897474105344/
