### ISSUE TITLE
chore: Remove hard coded text

### ISSUE THREAD

**Issue by abhijitramesh** [openMF/mifos-mobile-cn#70]
**Summary:**

There are some text that are hard-coded int the XML files of the project remove them by extracting them as sting resources

**Comment by PiyushSharma99** [comment]
I would like to work on this @abhijitramesh

**Comment by crowded-geek** [comment]
@abhijitramesh I just analyzed the project and actually no strings are hardcoded. It's already fixed!

**Comment by abhijitramesh** [comment]
@crowded-geek It was about the hard-coded text in xml files
