### ISSUE TITLE
feat: Add faq section in navigation drawer

### ISSUE THREAD

**Issue by sukhbeer** [openMF/mifos-mobile-cn#73]
**Summary:**

Add the faq section in the application

**Steps to reproduce:**

*  Open Application
*  Open Navigation drawer
*  No faq section

**Expected behaviour:**

 This task is to add faq functionality.

**Comment by sukhbeer** [comment]
@abhijitramesh add GCI tag.

**Comment by ashwinkey04** [comment]
I have added an option in the navbar for FAQ. For now, a toast will be displayed when that option is clicked. Should I go ahead and open a PR?

**Comment by sukhbeer** [comment]
Yeah, Go Ahead.
