### ISSUE TITLE
Bug: Add a confirmation dialog in forgot passcode

### ISSUE THREAD

**Issue by rachittt** [openMF/mifos-mobile-cn#86]
**Summary:**
When user clicks on "Forgot passcode, login manually", he is directed to login page directly. However a cofirmation dialog should confirm whether he/she really wants to login manually. This will enhance the User Experience.

**Steps to reproduce:**
1. Go to Passcode Activity
2. Click on "Forgot passcode, login manually" button
3. You will be directed to the Login Activity

**Expected behaviour:**
Before directing to the login activity, a dialog should pop up to confirm the action.
**Observed behaviour:**
.No Confirmation takes place

**Device and Android version:**

Device - Mi A2 
Android 9 Pie

GIF:
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/44428198/70230433-548bfd00-177e-11ea-9ca2-34b5ea2c99b3.gif)

**Comment by rachittt** [comment]
Can I start working on this issue ?

**Comment by harshshinde07** [comment]
@rachittt Unless and until any critical action is taking place, I don't really think there is a need for any kind of confirmation dialog. This situation does not cause any harm as such.

Take an example of log out button, when user logs out, he/she has to manually re-enter the login credentials. This task is critical as the user might have clicked the log out by mistake or even have forgotten the credentials. Only in such critical tasks we need a confirmation dialog.

**Comment by rachittt** [comment]
@harshshinde07 if a person clicks on the forgot passcode button by mistake, he has to manually enter the password as well as set up a new passcode and then confirm that passcode. I just thought maybe adding a confirmation dialog as we did in 'Mifos Mobile' would enhance the user experience of the User.

**Comment by harshshinde07** [comment]
Does it go back to the passcode activity on pressing back button?

**Comment by rachittt** [comment]
@harshshinde07 as of now, nope

**Comment by harshshinde07** [comment]
I personally don't think adding the dialog here is a good practice. So just redirecting it back to passcode should work for now. What are your thoughts @luckyman20 ?

**Comment by luckyman20** [comment]
@harshshinde07 well, we can add a confirmation dialog.

@rachittt Go ahead :)

**Comment by rachittt** [comment]
Cool! @luckyman20 Can you assign this task to me while I work on it ?

**Comment by luckyman20** [comment]
@rachittt Well, it is not necessary that you contribute through tasks only.
