### ISSUE TITLE
Improve the UI of the homescreen 

### ISSUE THREAD

**Issue by GOVINDDIXIT** [openMF/mifos-mobile-cn#89]
**Summary:**

There is a scope of UI improvement in the home screen of the app
Icons can be made smaller
Visit [this](https://dribbble.com/shots/7587490-MOLLET-Wallet-app-UI-Kit/attachments/372728?mode=media) for reference

**Steps to reproduce:**

Open the app

**Expected behaviour:**

Icons can be made smaller, Othe UI improvements will be appreciated

**Observed behaviour:**

Currently, the home screen has a scope of UI improvements

**Device and Android version:**

Android 9
Redmi Note 5 Pro
MIUI 10

**Screenshots:**

Open the app

**This issue is for GCI Students**

**Comment by sabya48** [comment]
ok i am working on this

**Comment by sabya48** [comment]
issue #89 i am working on it
