### ISSUE TITLE
Improve the UI of the Login Page

### ISSUE THREAD

**Issue by rachittt** [openMF/mifos-mobile-cn#98]
**Summary:**

There is a scope of UI Improvement in the login page. We should use material design.

**Expected outcome**

A visually appealing login page.

**Screenshot of the existing login page:**
![WhatsApp Image 2019-12-24 at 23 30 41](https://user-images.githubusercontent.com/44428198/71422112-6e49a180-26a5-11ea-9080-df546fba7dfc.jpeg)

**Suggestions:**
1. Remove the Action Bar
2. Use Material EditText for Login Form
3. Change the color scheme of the button and status bar.

**Comment by rachittt** [comment]
**I would like to propose the following design:**
![login-1](https://user-images.githubusercontent.com/44428198/71422516-adc5bd00-26a8-11ea-9136-4601c82d5392.png)

**Comment by refactor-droidyy** [comment]
@rachittt can I the background image since rest I can design?

**Comment by refactor-droidyy** [comment]
@rachittt please have a look
![oie_aDA5hJlFl8E9](https://user-images.githubusercontent.com/44283521/71425642-6b5ea900-26c5-11ea-8552-40a7f069a6c2.png)

**Comment by rachittt** [comment]
@refactor-droidyy let's first wait for the mentors to approve the design, then we can work on implementing it.
@abhijitramesh @harshshinde07 @luckyman20

**Comment by harshshinde07** [comment]
Hi, the usability research of this app is a GCI task this time as the whole app needs a redesign. I think the designs that have been proposed there are sent for approval. So once approved, the whole app will be redesigned not just the single page as it won't fit in with the design of rest of the app.

**Comment by rachittt** [comment]
> Hi, the usability research of this app is a GCI task this time as the whole app needs a redesign. I think the designs that have been proposed there are sent for approval. So once approved, the whole app will be redesigned not just the single page as it won't fit in with the design of rest of the app.

All right then, closing this issue.
